// <auto-generated />
namespace DAB32.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Postnummer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Postnummer));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291338426_added_Postnummer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
