// <auto-generated />
namespace DAB32.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_postnummerid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_postnummerid));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291334254_remove_postnummerid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
